name: ssld
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.10.0=py310haa95532_0
  - aom=3.6.1=h63175ca_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310h02ab6af_0
  - asttokens=3.0.0=py310haa95532_0
  - async-lru=2.0.4=py310haa95532_0
  - attrs=24.3.0=py310haa95532_0
  - babel=2.16.0=py310haa95532_0
  - beautifulsoup4=4.13.5=py310haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py310haa95532_0
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli-python=1.0.9=py310h5da7b33_9
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.16.0=h0ac17fb_1012
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.16=py310h885b0b7_0
  - decorator=5.2.1=py310haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=5.1.2=gpl_h8bb4bc8_112
  - filelock=3.17.0=py310haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.13.3=h0620614_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h7edc060_0
  - glib=2.84.0=h3d4babf_0
  - glib-tools=2.84.0=h4394cf3_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h11=0.16.0=py310haa95532_0
  - harfbuzz=6.0.0=he256f1b_0
  - httpcore=1.0.9=py310haa95532_0
  - httpx=0.28.1=py310haa95532_0
  - icu=70.1=h0e60522_0
  - idna=3.7=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.30.1=py310haa95532_0
  - ipython=8.30.0=py310haa95532_0
  - jasper=2.0.33=hc2e4405_1
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.9.25=py310haa95532_0
  - jsonschema=4.25.0=py310haa95532_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter-lsp=2.2.5=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - jupyter_events=0.12.0=py310haa95532_0
  - jupyter_server=2.16.0=py310haa95532_0
  - jupyter_server_terminals=0.5.3=py310haa95532_0
  - jupyterlab=4.4.7=py310haa95532_0
  - jupyterlab_pygments=0.3.0=py310haa95532_0
  - jupyterlab_server=2.27.3=py310haa95532_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=12_hb3dda5d_netlib
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.84.0=h7025463_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=12_h13b7882_netlib
  - liblapacke=3.9.0=12_h1360930_netlib
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.7.0=py310h90026ac_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.21.12=h12be248_2
  - libsodium=1.0.20=h83e8143_0
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib-base=3.10.6=py310h43afe63_0
  - matplotlib-inline=0.1.7=py310haa95532_0
  - mistune=3.1.2=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.10.2=py310haa95532_0
  - nbconvert-core=7.16.6=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - notebook=7.4.5=py310haa95532_0
  - notebook-shim=0.2.4=py310haa95532_0
  - numexpr=2.11.0=py310hdb065b2_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - opencv=4.7.0=py310h5588dad_1
  - openh264=2.3.1=h63175ca_2
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.4=h725018a_0
  - overrides=7.4.0=py310haa95532_0
  - packaging=25.0=py310haa95532_0
  - pandas=2.3.2=py310ha5e6156_0
  - pandocfilters=1.5.1=py310haa95532_0
  - parso=0.8.4=py310haa95532_0
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - prometheus_client=0.21.1=py310haa95532_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py310h02ab6af_0
  - pure_eval=0.2.3=py310haa95532_0
  - py-opencv=4.7.0=py310hbbfc1a7_1
  - pycparser=2.23=py310haa95532_0
  - pygments=2.19.1=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-fastjsonschema=2.20.0=py310haa95532_0
  - python-json-logger=3.2.1=py310haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py310haa95532_0
  - pywin32=311=py310h885b0b7_0
  - pywinpty=2.0.15=py310h72d21ff_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=27.1.0=py310h7149c55_0
  - qt-main=5.15.8=h720456b_6
  - referencing=0.30.2=py310haa95532_0
  - requests=2.32.5=py310haa95532_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rpds-py=0.22.3=py310h636fa0f_0
  - seaborn=0.13.2=py310haa95532_3
  - send2trash=1.8.2=py310haa95532_1
  - setuptools=78.1.1=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sniffio=1.3.0=py310haa95532_0
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py310haa95532_0
  - svt-av1=1.4.1=h63175ca_0
  - sympy=1.14.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.18.1=py310haa95532_0
  - tinycss2=1.4.0=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py310haa95532_0
  - tornado=6.5.1=py310h827c3e9_0
  - tqdm=4.67.1=py310h9909e9c_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py310h827c3e9_1
  - urllib3=2.5.0=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py310haa95532_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=1.8.0=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - winpty=0.4.3=4
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - blobfile==3.1.0
      - chardet==5.2.0
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.1
      - ipywidgets==8.1.8
      - joblib==1.5.2
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - markdown==3.9
      - mpi4py==4.1.0
      - platformdirs==4.4.0
      - protobuf==6.32.1
      - pycryptodomex==3.23.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyparsing==3.2.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentry-sdk==2.39.0
      - smmap==5.0.2
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - typing-inspection==0.4.2
      - wandb==0.22.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
prefix: C:\Users\SHREY\anaconda3\envs\ssld
